name: google_search_place
description: Custom Google search places autocomplete widget for all platform. Use https://pub.dev/packages/google_search_place
version: 0.0.4
homepage: https://github.com/nareshonly851/google_search_place

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1+1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
